export const GET_ALL_SEATS = "GET_ALL_SEATS";
export const GET_SCHEDULE_MOVIE_DETAIL = "GET_SCHEDULE_MOVIE_DETAIL";
export const BOOKING_TICKET = "BOOKING_TICKET";
export const BOOKING_SEAT = "BOOKING_SEAT";
export const OTHER_BOOKING_SEAT = "OTHER_BOOKING_SEAT";
export const BOOKING_SEATS_SUCCESS = "BOOKING_SEATS_SUCCESS";
